spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springstudy
    username: root
    password: 4890
  data:
    redis:
      host: localhost
      port: 6379
      password:

application:
  jwt:
    expiration: 3000000
    refresh-expiration: 604800000
    secret-key: ${SECRET_KEY}
